apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          imagePullPolicy: Never
          ports:
          - containerPort: 3000
          volumeMounts:
          - name: volume200
            mountPath: /var/lib/influxdb
      volumes:
        - name: volume200
          persistentVolumeClaim:
            claimName: pvc2
---
kind: Service
apiVersion: v1
metadata:
  name: influxdb-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: influxdb
  ports:
  - port: 3000
  selector:
    app: influxdb
  clusterIP: None
  

  
